name: Build Flutter APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.3'
        channel: 'stable'
        
    - name: Clean and Build APK
      run: |
        flutter clean
        flutter pub cache clean
        flutter pub get
        flutter pub upgrade --major-versions
        flutter build apk --debug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: build/app/outputs/flutter-apk/app-debug.apk
