
name: Build APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
          
      - name: Clean old folders
        run: rm -rf android ios lib
        
      - name: Create Flutter Project
        run: flutter create --org com.changa --project-name changa_app .
        
      - name: Fix Android Config
        run: |
          sed -i 's/compileSdk 34/compileSdk 35/g' android/app/build.gradle
          sed -i 's/minSdk 21/minSdk 23/g' android/app/build.gradle
          sed -i 's/targetSdk 34/targetSdk 35/g' android/app/build.gradle
          echo "include ':app'" > android/settings.gradle
        
      - name: Get dependencies
        run: flutter pub get
        
      - name: Build APK
        run: flutter build apk --release
        
      - uses: actions/upload-artifact@v4
        with:
          name: changa-app
          path: build/app/outputs/flutter-apk/app-release.apk
